import type { SiteContent, MenuContent } from "./types";

export const DEFAULT_CONTENT: SiteContent = {
  images: {
    heroPoster: "/assets/img/hero-cephe.webp",
    heroCephe: "/assets/img/hero-cephe.webp",
    heroIc: "/assets/img/hero-ic.webp",
    aboutInterior: "/assets/img/ic-mekan.jpg",
    ogImage: "/assets/img/urun/vitrin-hamur.jpg",
    logo: "/assets/img/logo.webp",
    favicon: "/assets/img/favicon-96.png",
  },
  navbar: {
    logoText: "FIRINCI",
    logoSize: 64,
    logoTextGizle: true,
    mobileLabel: "Menü",
    ctaLabel: "0552 340 02 02",
    ctaHref: "tel:+905523400202",
    links: [
      { label: "Hakkımızda", href: "#hakkimizda" },
      { label: "Ürünler", href: "urunler/urunler" },
      { label: "Özel Pastalar", href: "#pasta" },
      { label: "Galeri", href: "#galeri" },
      { label: "Yorumlar", href: "#yorumlar" },
      { label: "S.S.S.", href: "#sss" },
      { label: "Fırın Günlüğü", href: "blog/blog" },
      { label: "İletişim", href: "#iletisim" },
    ],
  },
  hero: {
    fallbackMark: "FIRINCI",
    fallbackTagline: "Taze · Lezzetli · Doğal",
    scrollHint: "Aşağı kaydırın",
    welcomeAktif: false,
    welcomeEyebrow: "Taşdelen Fırıncı",
    welcomeTitle: "Hoş Geldiniz",
    welcomeLead: "Her gün taze ekmek, sıcak poğaça ve özenle hazırlanan lezzetler.",
    doorUv: { u0: 0.368, u1: 0.633, v0: 0.552, v1: 1 },
  },
  marquee: [
    "TAZE EKMEK",
    "GÜNLÜK ÜRETİM",
    "ÖZEL TASARIM PASTA",
    "SİMİT & POĞAÇA",
    "ÇEKMEKÖY TAŞDELEN",
    "DOĞAL MALZEME",
    "BAKLAVA & BÖREK",
    "HER GÜN TAPTAZE",
    "EL YAPIMI LEZZETLER",
    "GELENEKSEL TARİF",
  ],
  duyuru: { aktif: false, metin: "" },
  hakkimizda: {
    eyebrow: "Hakkımızda",
    baslik: "Taşdelen'in fırını ve pastanesi",
    answerBaslik: "Kısaca",
    answerMetin:
      "Taşdelen Fırıncı, Çekmeköy Taşdelen'de bulunan bir fırın ve pastanedir. Her gün taze üretilen ekmek, simit, poğaça, börek, kurabiye, baklava ve pasta çeşitleri sunar; şeker hamurlu özel tasarım pasta siparişi alır. Adres: Turgut Özal Caddesi No:108/C, Bulvar Rezidans A Blok. Sipariş: 0552 340 02 02.",
    lead: "Çekmeköy Taşdelen'de yer alan fırınımızda, doğal ve taze ürünlerle müşterilerimize kaliteli hizmet sunmayı; lezzet ve güveni ön planda tutmayı amaçlıyoruz.",
    body: [
      "Geleneksel lezzetleri kaliteli malzemelerle buluşturuyor, her gün sıcak ve taze ürünlerimizi sizlerle paylaşıyoruz. Ekmekten tatlıya uzanan geniş çeşidimizle, sabah kahvaltınızdan özel gününüzün pastasına kadar yanınızdayız.",
      "Fırınımız Taşdelen Mahallesi'nde, Turgut Özal Caddesi üzerindeki Bulvar Rezidans'ın önünde yer alıyor. Taşdelen, Alemdağ ve Çekmeköy çevresinden gelen komşularımıza 7 gün 24 saat taze ürün sunuyoruz; cadde üzerinde ücretsiz park imkânı bulunuyor.",
      "Kahvaltı sofranız için: susamlı simit, tereyağlı simit, sade ve peynirli poğaça, kaşarlı açma, tereyağlı kol böreği ve günlük ekmek çeşitlerimiz sabahın erken saatlerinden itibaren tezgâhta bulunur. Gece de açık olduğumuz için sabah kahvaltısını erken kuranlar bizi hazır bulur.",
    ],
    ozet: [
      { b: "Her gün", span: "taze & sıcak üretim" },
      { b: "14", span: "ürün kategorisi" },
      { b: "130+", span: "farklı ürün çeşidi" },
      { b: "7/24", span: "Taşdelen'de açık" },
    ],
    badgeBaslik: "Taze",
    badgeAlt: "Lezzetli · Doğal",
  },
  bolumlar: {
    menu: { eyebrow: "Menü", baslik: "Günlük üretimden seçmeler", lead: "Her gün taze pişen ekmek, simit, poğaça ve tatlı çeşitlerimiz." },
    galeri: { eyebrow: "Galeri", baslik: "Lezzet galerimiz", lead: "Fırınımızda günlük olarak hazırlanan ürünlerimizi keşfedin." },
    yorumlar: { eyebrow: "Müşteri Yorumları", baslik: "Deneyimleyenlerin Gözünden", lead: "Taşdelen Fırıncı’yı tercih edenlerin gerçek deneyimleri." },
    sss: { eyebrow: "Sık Sorulanlar", baslik: "Merak edilenler" },
  },
  pasta: {
    eyebrow: "Özel Tasarım",
    baslik: "Şeker hamurlu özel tasarım pastalar",
    lead: "Hayal ettiğiniz pastayı birlikte tasarlıyoruz. Doğum günü, nişan ve tüm özel günleriniz için tamamen size özel pastalar.",
    maddeler: ["Kişiye özel tasarım", "Taze ve kaliteli malzemeler", "İstenilen tema ve figürler", "Lezzet ve görselliğin mükemmel uyumu"],
    body: "Sipariş ve detaylı bilgi için bizimle iletişime geçebilirsiniz.",
    ctaLabel: "Pasta Siparişi İçin Arayın",
    ctaHref: "tel:+905523400202",
    gorseller: [
      { src: "/assets/img/urun/pasta-gul.jpg", alt: "Güllerle süslenmiş özel tasarım pasta" },
      { src: "/assets/img/urun/pasta-safari.jpg", alt: "Safari temalı figürlü pasta" },
      { src: "/assets/img/urun/pasta-kanat.jpg", alt: "Altın kanat detaylı pasta" },
      { src: "/assets/img/urun/pasta-drip.jpg", alt: "Pembe akıtmalı doğum günü pastası" },
      { src: "/assets/img/urun/pasta-cocuk-1.jpg", alt: "Çizgi film karakterli çocuk pastası" },
      { src: "/assets/img/urun/pasta-cocuk-2.jpg", alt: "Süper kahraman temalı çocuk pastası" },
      { src: "/assets/img/urun/pasta-marka.jpg", alt: "Marka detaylı özel pasta" },
      { src: "/assets/img/urun/pasta-tac.jpg", alt: "Altın taç detaylı pasta" },
    ],
  },
  makaleler: [
    { slug: "pasta-siparisi-rehberi", baslik: "Doğum günü pastası siparişi: kaç kişilik, ne zaman verilir?", ozet: "Kişi sayısına göre pasta boyu, kaç saat önceden sipariş vermeniz gerektiği, yazı ve figür seçenekleri.", kategori: "Pastane", tarih: "21 Temmuz 2026", yayinda: true, statik: true },
    { slug: "hangi-ekmek-kime-uygun", baslik: "Tam buğday, çavdar, siyez: hangi ekmek kime uygun?", ozet: "Un çeşitlerinin lif, mineral ve glüten farkları; kan şekeri ve sindirim açısından karşılaştırma.", kategori: "Ekmek", tarih: "9 Temmuz 2026", yayinda: true, statik: true },
    { slug: "ekmek-nasil-saklanir", baslik: "Ekmek nasıl saklanır? Taze kalması için 7 kural", ozet: "Buzdolabı neden ekmeği bayatlatır, poşet mi bez mi, dilimlenmiş ekmek nasıl dondurulur.", kategori: "Pratik Bilgi", tarih: "28 Haziran 2026", yayinda: true, statik: true },
    { slug: "eksi-maya-ekmek-nedir", baslik: "Ekşi mayalı ekmek nedir? Neden tercih edilir?", ozet: "Ekşi mayanın fermantasyon süreci, sindirim ve lezzet farkları, hangi ürünlerimizde kullanıldığı.", kategori: "Maya", tarih: "12 Haziran 2026", yayinda: true, statik: true },
  ],
  manifesto: { ustBaslik: "Lezzet geleneği", satirlar: [] },
  hikaye: null,
  menu: null as MenuContent | null,
  galeri: [
    { src: "/assets/img/cephe.jpg", baslik: "Fırınımız · Taşdelen", boy: "wide" },
    { src: "/assets/img/kapi.jpg", baslik: "Giriş", boy: "half" },
    { src: "/assets/img/urun/vitrin-pasta.jpg", baslik: "Pasta vitrini", boy: "half" },
    { src: "/assets/img/urun/ekmek-rustik.jpg", baslik: "Somunlar", boy: "third" },
    { src: "/assets/img/urun/vitrin-hamur.jpg", baslik: "Hamur işleri", boy: "third" },
    { src: "/assets/img/urun/simit.jpg", baslik: "Sıcacık simit", boy: "third" },
  ],
  yorumlar: [
    { metin: "Ekibinizin sıcak ve samimi hizmeti sayesinde unutulmaz bir tatlı anı yaşadığımı belirtmek isterim.", ad: "Ayşe Yılmaz", unvan: "Öğretmen", yildiz: 5 },
    { metin: "Her ürününde kalite ve özen gözeten Taşdelen Fırıncı, beklentilerimi fazlasıyla karşıladı.", ad: "Mehmet Demir", unvan: "Mühendis", yildiz: 5 },
    { metin: "Kızımın doğum günü için istediğimiz temada pasta hazırladılar, hem görüntüsü hem lezzeti çok beğenildi.", ad: "Zeynep Kaya", unvan: "Taşdelen sakini", yildiz: 5 },
    { metin: "Sabahları taze simit ve poğaça için uğruyoruz; lezzet hiç düşmüyor, personel her zaman güler yüzlü.", ad: "Elif Arslan", unvan: "Çekmeköy", yildiz: 5 },
    { metin: "Özel gün pastamız zamanında ve istediğimiz gibi geldi. Taşdelen’de güvenle sipariş verdiğimiz adres.", ad: "Burak Özkan", unvan: "İşletmeci", yildiz: 5 },
  ],
  sss: { items: [
    { soru: "Sipariş nasıl verilir?", cevap: "Telefon veya WhatsApp ile 0552 340 02 02 üzerinden sipariş verebilirsiniz." },
    { soru: "Hangi saatlerde açıksınız?", cevap: "7 gün, sabah ve öğle saatlerinde taze ürünlerimiz olur; özel günlerde farklılık gösterebilir." },
  ] },
  iletisim: {
    baslik: "Her gün taze, sıcak ve lezzetli",
    giris: "Sipariş, özel tasarım pasta ve tüm sorularınız için bizi arayabilir ya da WhatsApp'tan yazabilirsiniz.",
    metin: "Doğum günü, nişan, söz, baby shower ve tüm özel günleriniz için kişiye özel pasta siparişleri alınır.",
    eyebrow: "İletişim",
    telefon: "0552 340 02 02",
    telefonHam: "+905523400202",
    telefonAlt: "Sipariş & İletişim - 7/24",
    whatsapp: "https://wa.me/905523400202",
    whatsappBaslik: "WhatsApp'tan yazın",
    whatsappAlt: "Hızlı Sipariş ve Bilgi",
    instagram: "@firincitasdelenn",
    instagramUrl: "https://www.instagram.com/firincitasdelenn/",
    instagramAlt: "Günün Fotoğrafları Instagram'da",
    eposta: "info@firincitasdelen.com.tr",
    epostaAlt: "E-posta",
    adresSatir1: "Taşdelen Mah. Turgut Özal Cad. No:108/C",
    adresSatir2: "Bulvar Rezidans A Blok",
    adresSatir3: "Çekmeköy / İstanbul",
    saatler: "7 gün 24 saat açık",
    ozelPastaNot: "Özel pasta siparişleri alınır",
    koordinat: "41.031267,29.229361",
    haritaSorgu: "41.031267,29.229361",
    haritaButonMetin: "Yol Tarifi Al",
    etiketAdres: "Adres",
    etiketSaatler: "Çalışma saatleri",
    etiketTelefon: "Telefon",
    etiketWhatsapp: "WhatsApp",
    etiketOzelPasta: "Özel pasta",
  },
  sayfalar: {
    urunler: {
      eyebrow: "Ürünler",
      baslikSablon: "{n} kategoride {m} çeşit",
      lead: "Her gün taze pişen ekmek, simit, poğaça, börek, tatlı ve pasta çeşitlerimiz.",
    },
    urunKategori: {
      eyebrow: "Ürünler",
      answerBaslik: "Kısa bilgi",
      listeBaslikSablon: "{ad} listesi",
      kartNot: "★ işaretliler en çok tercih edilenler. Ürüne tıklayarak WhatsApp’tan sipariş verebilirsiniz.",
      ctaBaslik: "Sipariş & bilgi",
      ctaWaLabel: "WhatsApp’tan yazın",
      relatedBaslik: "Diğer kategoriler",
      relatedHepsi: "Tüm ürün kategorileri",
    },
    blog: {
      eyebrow: "Fırın Günlüğü",
      baslik: "Ekmeğin ardındaki bilgi",
      lead: "Pasta siparişi, ekmek saklama, un çeşitleri ve fırın mutfağından pratik yazılar.",
      ctaBaslik: "Aklınıza takılan bir şey mi var?",
      ctaMetin: "Sipariş ve sorularınız için bizi arayın veya WhatsApp’tan yazın.",
    },
  },
  seo: {
    title: "Taşdelen Fırıncı — Fırın ve Pastane | Çekmeköy Taşdelen",
    description:
      "Çekmeköy Taşdelen'de 7/24 açık fırın ve pastane. Her gün taze ekmek, simit, poğaça, börek, kurabiye, baklava, tatlı ve yaş pasta; şeker hamurlu özel tasarım pastalar. Sipariş: 0552 340 02 02",
    ogTitle: "Taşdelen Fırıncı — Fırın ve Pastane | Çekmeköy",
    ogDescription:
      "Çekmeköy Taşdelen'de 7/24 açık fırın ve pastane. Taze ekmek, simit, poğaça, börek, tatlı, yaş pasta ve özel tasarım pastalar.",
    siteName: "Taşdelen Fırıncı",
    canonicalUrl: "https://www.firincitasdelen.com.tr/",
    themeColor: "#12140E",
  },
  footer: {
    markaAdi: "Taşdelen Fırıncı",
    yasalMetin: "Tüm hakları saklıdır.",
    slogan: "Taze • Lezzetli • Doğal\nÇekmeköy Taşdelen'de her gün taptaze.",
    kolonlar: [
      {
        baslik: "Fırın",
        links: [
          { label: "Hakkımızda", href: "#hakkimizda" },
          { label: "Ürünler", href: "/urunler/urunler" },
          { label: "Özel Pastalar", href: "#pasta" },
          { label: "Galeri", href: "#galeri" },
          { label: "Fırın Günlüğü", href: "/blog/blog" },
        ],
      },
      {
        baslik: "Adres",
        links: [
          { label: "Turgut Özal Cad. No:108/C", href: "#iletisim" },
          { label: "Bulvar Rezidans A Blok", href: "#iletisim" },
          { label: "Çekmeköy / İstanbul", href: "#iletisim" },
          { label: "7/24 açık", href: "#iletisim" },
        ],
      },
      {
        baslik: "İletişim",
        links: [
          { label: "0552 340 02 02", href: "tel:+905523400202" },
          { label: "WhatsApp", href: "https://wa.me/905523400202" },
          { label: "Instagram", href: "https://www.instagram.com/firincitasdelenn/" },
          { label: "info@firincitasdelen.com.tr", href: "mailto:info@firincitasdelen.com.tr" },
        ],
      },
    ],
  },
  waFloat: {
    baslik: "WhatsApp Sipariş",
    alt: "7/24 Hızlı Yanıt",
    onYazi: "Merhaba, Taşdelen Fırıncı’ya sipariş vermek istiyorum.",
    ariaLabel: "WhatsApp ile sipariş verin",
  },
  legal: {
    kvkk: "Kişisel verileriniz 6698 sayılı KVKK kapsamında yalnızca sipariş ve iletişim amaçlı işlenir.",
    gizlilik: "Gizlilik politikamız: iletişim bilgileriniz üçüncü taraflarla paylaşılmaz.",
    cerez: "Bu site temel işlevler için zorunlu çerezler kullanır.",
  },
  brand: {
    displayName: "Taşdelen Fırıncı",
    shortName: "FIRINCI",
  },
  yorumlarMeta: {
    googleSayacMetin: "30+ Google Yorumu",
    googleSkor: "4.87 / 5.0",
    dogrulamaEtiketi: "Doğrulanmış Google Yorumu",
    googleUrl: "https://www.google.com/maps/search/?api=1&query=Ta%C5%9Fdelen+F%C4%B1r%C4%B1nc%C4%B1+%C3%87ekmek%C3%B6y",
    badgeCta: "Google’da gör",
    unvanVarsayilan: "Müşteri",
  },
};

export function mergeContent(partial: Partial<SiteContent>, current: SiteContent): SiteContent {
  return {
    ...current,
    ...partial,
    images: partial.images ? { ...current.images, ...partial.images } : current.images,
    navbar: partial.navbar ? { ...current.navbar, ...partial.navbar, links: partial.navbar.links ?? current.navbar.links } : current.navbar,
    hero: partial.hero ? { ...current.hero, ...partial.hero } : current.hero,
    duyuru: partial.duyuru ? { ...current.duyuru, ...partial.duyuru } : current.duyuru,
    hakkimizda: partial.hakkimizda ? { ...current.hakkimizda, ...partial.hakkimizda } : current.hakkimizda,
    bolumlar: partial.bolumlar ? { ...current.bolumlar, ...partial.bolumlar } : current.bolumlar,
    pasta: partial.pasta ? { ...current.pasta, ...partial.pasta } : current.pasta,
    iletisim: partial.iletisim ? { ...current.iletisim, ...partial.iletisim } : current.iletisim,
    menu: partial.menu !== undefined ? partial.menu : current.menu,
    hikaye: partial.hikaye !== undefined ? partial.hikaye : current.hikaye,
    manifesto: partial.manifesto ? { ...current.manifesto, ...partial.manifesto } : current.manifesto,
    makaleler: partial.makaleler ?? current.makaleler,
    galeri: partial.galeri ?? current.galeri,
    yorumlar: partial.yorumlar ?? current.yorumlar,
    sss: partial.sss ?? current.sss,
    marquee: partial.marquee ?? current.marquee,
    seo: partial.seo ? { ...current.seo, ...partial.seo } : current.seo,
    footer: partial.footer
      ? {
          ...current.footer,
          ...partial.footer,
          kolonlar: partial.footer.kolonlar ?? current.footer.kolonlar,
        }
      : current.footer,
    waFloat: partial.waFloat ? { ...current.waFloat, ...partial.waFloat } : current.waFloat,
    legal: partial.legal ? { ...current.legal, ...partial.legal } : current.legal,
    yorumlarMeta: partial.yorumlarMeta
      ? { ...current.yorumlarMeta, ...partial.yorumlarMeta }
      : current.yorumlarMeta,
    yorumlarSource: partial.yorumlarSource ?? current.yorumlarSource,
    yorumlarApi: partial.yorumlarApi ?? current.yorumlarApi,
    sayfalar: partial.sayfalar
      ? {
          urunler: { ...(current.sayfalar?.urunler || DEFAULT_CONTENT.sayfalar!.urunler), ...partial.sayfalar.urunler },
          urunKategori: {
            ...(current.sayfalar?.urunKategori || DEFAULT_CONTENT.sayfalar!.urunKategori),
            ...partial.sayfalar.urunKategori,
          },
          blog: { ...(current.sayfalar?.blog || DEFAULT_CONTENT.sayfalar!.blog), ...partial.sayfalar.blog },
        }
      : current.sayfalar || DEFAULT_CONTENT.sayfalar,
    brand: partial.brand
      ? { ...(current.brand || DEFAULT_CONTENT.brand!), ...partial.brand }
      : current.brand || DEFAULT_CONTENT.brand,
  };
}
