export interface PageUrlOption {
  label: string;
  value: string;
}

export const SITE_PAGE_URLS: PageUrlOption[] = [
  { label: "Menü", value: "/menu" },
  { label: "Kahvaltı", value: "/menu/kahvalti" },
  { label: "Menemen · Omlet · Gözleme", value: "/menu/menemen-omlet-gozleme" },
  { label: "Sandviçler", value: "/menu/sandvicler" },
  { label: "Tostlar", value: "/menu/tostlar" },
  { label: "Makarnalar", value: "/menu/makarnalar" },
  { label: "Pizzalar", value: "/menu/pizzalar" },
  { label: "Salatalar", value: "/menu/salatalar" },
  { label: "Izgaralar", value: "/menu/izgaralar" },
  { label: "Beyaz Etler", value: "/menu/beyaz-etler" },
  { label: "Dürümler", value: "/menu/durumler" },
  { label: "Ekstralar", value: "/menu/ekstralar" },
  { label: "Hamburger", value: "/menu/hamburger" },
  { label: "Tatlılar", value: "/menu/tatlilar" },
  { label: "Kahve ve Sıcak İçecekler", value: "/menu/kahve" },
  { label: "Soğuk Kahveler", value: "/menu/soguk-kahveler" },
  { label: "Milkshake", value: "/menu/milkshakes" },
  { label: "Bitki Çayları", value: "/menu/bitki-caylari" },
  { label: "Smoothie", value: "/menu/smoothie" },
  { label: "Kokteyller", value: "/menu/kokteyller" },
  { label: "Frozen", value: "/menu/frozen" },
  { label: "Soğuk İçecekler", value: "/menu/icecekler" },
  { label: "Ev Yapımı İçecekler", value: "/menu/ev-yapimi-icecekler" },
  { label: "Nargile", value: "/menu/nargile" },
  { label: "Ana Sayfa - Hakkımızda (#hakkimizda)", value: "#hakkimizda" },
  { label: "Ana Sayfa - Hizmetler (#hizmetler)", value: "#hizmetler" },
  { label: "Ana Sayfa - Menü (#menu)", value: "#menu" },
  { label: "Ana Sayfa - Havuz & Plaj (#pasta)", value: "#pasta" },
  { label: "Ana Sayfa - Rezervasyon (#rezervasyon)", value: "#rezervasyon" },
  { label: "Ana Sayfa - Galeri (#galeri)", value: "#galeri" },
  { label: "Ana Sayfa - Yorumlar (#yorumlar)", value: "#yorumlar" },
  { label: "Ana Sayfa - S.S.S. (#sss)", value: "#sss" },
  { label: "Ana Sayfa - İletişim (#iletisim)", value: "#iletisim" },
  { label: "Blog", value: "/blog" },
];
